Repository Tadeo-2404/FullStack-App-Vivero, pull requests merged in 2023-04, with the labels that each got.

#15 Creando las rutas y el controller para entidad cliente
  backend/controllers/ClienteController.js
  backend/index.js
  backend/routes/clienteRoutes.js
Labels: enhancement

#22 Creando el modelo de administrador
  backend/controllers/ClienteController.js
  backend/models/AdminModel.js
  backend/routes/clienteRoutes.js
Labels: enhancement

#30 Creando script .sql para la base de datos
  db_information/database.sql
Labels: documentation

#31 Entidad admin: Creando las rutas, el controller y la ruta general en el index.js
  backend/controllers/AdminController.js
  backend/index.js
  backend/routes/adminRoutes.js
Labels: enhancement

#33 Creando el modelo de sucursal
  backend/models/SucursalModel.js
Labels: enhancement

#34 Agregando formularios y estilos
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/pages/FormEditarProducto.jsx
  frontend/src/pages/FormPublicarProducto.jsx
  frontend/src/pages/admin/FormEditarProducto.jsx
  frontend/src/pages/admin/FormPublicarProducto.jsx
Labels: enhancement

#35 Creando el modelo empleado
  backend/models/ClienteModel.js
  backend/models/EmpleadoModel.js
Labels: enhancement

#36 Creando el modelo sustrato
  backend/models/SustratoModel.js
Labels: enhancement

#38 Organizando rutas /cliente y /admin, usando Layouts
  backend/controllers/ClienteController.js
  backend/routes/clienteRoutes.js
  frontend/src/App.jsx
  frontend/src/layout/TemplateLayoutAdmin.jsx
  frontend/src/layout/TemplateLayoutCliente.jsx
  frontend/src/pages/cliente/IniciarSesion.jsx
  frontend/src/pages/cliente/Registro.jsx
  frontend/src/pages/cliente/Sucursales.jsx
Labels: bug, enhancement

#32 Consistencia de rutas BACKEND
  backend/controllers/ClienteController.js
  backend/routes/adminRoutes.js
  backend/routes/clienteRoutes.js
Labels: bug, help wanted

#43 Creando API, controller y routes de productos y corrigiendo modelo
  backend/controllers/ProductoController.js
  backend/db/db.js
  backend/index.js
  backend/models/ProductoModel.js
  backend/routes/productoRoutes.js
  frontend/src/App.css
  frontend/src/App.jsx
Labels: enhancement

#46 Agregando controller, routes y API de sustrato
  backend/controllers/SustratoController.js
  backend/index.js
  backend/models/SustratoModel.js
  backend/routes/productoRoutes.js
  backend/routes/sustratoRoutes.js
  db_information/database.sql
Labels: enhancement

#49 Limite peticion productos, useArticulos, galeria de productos y sustratos
  backend/controllers/ProductoController.js
  backend/controllers/SustratoController.js
  backend/models/AdminModel.js
  backend/models/ClienteModel.js
  backend/models/EmpleadoModel.js
  backend/models/ProductoModel.js
  backend/models/SucursalModel.js
  backend/models/SustratoModel.js
  db_information/database.sql
  frontend/hooks/useArticulos.jsx
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/CardArticulo.jsx
  frontend/src/components/CardProducto.jsx
  frontend/src/components/GaleriaArticulos.jsx
  frontend/src/components/GaleriaProductos.jsx
  frontend/src/pages/Inicio.jsx
  frontend/src/pages/Productos.jsx
  frontend/src/pages/Sustratos.jsx
Labels: enhancement

#51 Modificando FormEditarArticulo para actualizar articulos
  frontend/hooks/useArticulos.jsx
  frontend/src/App.jsx
  frontend/src/components/GaleriaArticulos.jsx
  frontend/src/pages/Inicio.jsx
  frontend/src/pages/admin/FormEditarArticulo.jsx
  frontend/src/pages/admin/FormEditarProducto.jsx
Labels: enhancement

#53 Creando Login y Registrar Cuenta para el Administrador
  backend/.env
  backend/controllers/AdminController.js
  backend/helpers/generarJWT.js
  backend/index.js
  backend/models/AdminModel.js
  backend/package-lock.json
  backend/package.json
  backend/routes/adminRoutes.js
  db_information/database.sql
Labels: enhancement

#54 Admin: Creando controllers para restablecer contraseña
  backend/controllers/AdminController.js
  backend/helpers/generarToken.js
  backend/models/AdminModel.js
  backend/models/ClienteModel.js
  backend/package-lock.json
  backend/package.json
  backend/routes/adminRoutes.js
  db_information/database.sql
Labels: enhancement

#69 Eliminando Sucursal
  backend/models/SucursalModel.js
  db_information/database.sql
  db_information/diccionario_datos/tabla_sucursal.jpg
  frontend/src/pages/Sucursales.jsx
Labels: bug, invalid

#70 Eliminando entidad sustrato
  backend/index.js
  backend/models/SustratoModel.js
  backend/routes/sustratoRoutes.js
  db_information/diccionario_datos/tabla_sustrato.jpg
  frontend/src/pages/Sustratos.jsx
Labels: bug

#72 Eliminando entidad empleado
  backend/models/EmpleadoModel.js
  db_information/database.sql
  db_information/diccionario_datos/tabla_empleado.jpg
Labels: bug, invalid

#74 Creando modelo y API Proveedor
  backend/controllers/ProveedorController.js
  backend/index.js
  backend/models/ProveedorModel.js
  backend/routes/proveedorRoutes.js
Labels: enhancement

#76 Creando Modelo, Controllers y Rutas de Ventas
  backend/controllers/VentaController.js
  backend/index.js
  backend/models/VentaModel.js
  backend/routes/ventaRoutes.js
  db_information/database.sql
Labels: enhancement

#78 Creando modelo, controllers, rutas VentaProductos
  backend/controllers/VentaController.js
  backend/controllers/VentaProductoController.js
  backend/index.js
  backend/models/VentaProductoModel.js
  backend/routes/ventaProductosRouter.js
Labels: enhancement

#81 Corrigiendo errores del backend
  backend/controllers/AdminController.js
  backend/controllers/ProveedorController.js
  backend/controllers/VentaController.js
  backend/controllers/VentaProductoController.js
  backend/helpers/utils.js
  backend/index.js
  backend/models/VentaModel.js
  backend/models/VentaProductoModel.js
  backend/routes/ventaProductosRouter.js
  backend/routes/ventaRoutes.js
Labels: bug, invalid

#86 Creando formulario de ventas
  backend/controllers/VentaController.js
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/pages/admin/FormAgregarVenta.jsx
Labels: enhancement
